### ISSUE TITLE
enable/disable programmatically?

### ISSUE THREAD

**Issue by bryanbuchs** [tannerhodges/match-height#2]
Nice utility! I'm poking through `src/match-height.js` and it doesn't look like there's any way to set the enable/disable breakpoint options when using `MatchHeight.add()`. Am I missing anything?

**Comment by tannerhodges** [comment]
Hey @bryanbuchs!

Right now, the only way to enable/disable breakpoints is to add the `data-match-height-enable` on a parent/container element.

```js
const container = document.querySelector('.example');
const elements = container.querySelectorAll('.example__heading');

// Enable/disable breakpoints on your container.
container.setAttribute('data-match-height-enable', '(min-width: 600px)');

// Add your elements.
MatchHeight.add(elements);
```

Here's a quick CodePen example: https://codepen.io/tannerhodges/pen/fd41f15449b13a587d9d5149c6d9778a

I realize that's not really documented anywhere, though… I'll have to clear that up in the readme.

🤔 There may be an opportunity to provide another JS method for this, but I'm not sure how I'd specify the container for the group. Unless we added something like `MatchHeight.enable(container, breakpoint)`? ← My main concern with this syntax is whether it's clear what `container` should be (i.e., that it's a single container element, not the group of elements you're trying to enable/disable). Thoughts?

**Comment by bryanbuchs** [comment]
Thanks for the codepen!  Using `setAttribute` on my parent should be enough for my purposes right now.
